package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * ActorInfo generated by hbm2java
 */
public class ActorInfo  implements java.io.Serializable {


     private ActorInfoId id;

    public ActorInfo() {
    }

    public ActorInfo(ActorInfoId id) {
       this.id = id;
    }
   
    public ActorInfoId getId() {
        return this.id;
    }
    
    public void setId(ActorInfoId id) {
        this.id = id;
    }




}


