package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * CustomerList generated by hbm2java
 */
public class CustomerList  implements java.io.Serializable {


     private CustomerListId id;

    public CustomerList() {
    }

    public CustomerList(CustomerListId id) {
       this.id = id;
    }
   
    public CustomerListId getId() {
        return this.id;
    }
    
    public void setId(CustomerListId id) {
        this.id = id;
    }




}


