package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * Film2 generated by hbm2java
 */
public class Film2  implements java.io.Serializable {


     private Film2Id id;

    public Film2() {
    }

    public Film2(Film2Id id) {
       this.id = id;
    }
   
    public Film2Id getId() {
        return this.id;
    }
    
    public void setId(Film2Id id) {
        this.id = id;
    }




}


