package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * FilmList generated by hbm2java
 */
public class FilmList  implements java.io.Serializable {


     private FilmListId id;

    public FilmList() {
    }

    public FilmList(FilmListId id) {
       this.id = id;
    }
   
    public FilmListId getId() {
        return this.id;
    }
    
    public void setId(FilmListId id) {
        this.id = id;
    }




}


