package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * Film6 generated by hbm2java
 */
public class Film6  implements java.io.Serializable {


     private Film6Id id;

    public Film6() {
    }

    public Film6(Film6Id id) {
       this.id = id;
    }
   
    public Film6Id getId() {
        return this.id;
    }
    
    public void setId(Film6Id id) {
        this.id = id;
    }




}


