package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * Maxsommes generated by hbm2java
 */
public class Maxsommes  implements java.io.Serializable {


     private MaxsommesId id;

    public Maxsommes() {
    }

    public Maxsommes(MaxsommesId id) {
       this.id = id;
    }
   
    public MaxsommesId getId() {
        return this.id;
    }
    
    public void setId(MaxsommesId id) {
        this.id = id;
    }




}


