package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * NicerButSlowerFilmList generated by hbm2java
 */
public class NicerButSlowerFilmList  implements java.io.Serializable {


     private NicerButSlowerFilmListId id;

    public NicerButSlowerFilmList() {
    }

    public NicerButSlowerFilmList(NicerButSlowerFilmListId id) {
       this.id = id;
    }
   
    public NicerButSlowerFilmListId getId() {
        return this.id;
    }
    
    public void setId(NicerButSlowerFilmListId id) {
        this.id = id;
    }




}


