package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * SalesByFilmCategory generated by hbm2java
 */
public class SalesByFilmCategory  implements java.io.Serializable {


     private SalesByFilmCategoryId id;

    public SalesByFilmCategory() {
    }

    public SalesByFilmCategory(SalesByFilmCategoryId id) {
       this.id = id;
    }
   
    public SalesByFilmCategoryId getId() {
        return this.id;
    }
    
    public void setId(SalesByFilmCategoryId id) {
        this.id = id;
    }




}


