package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * SalesByStore generated by hbm2java
 */
public class SalesByStore  implements java.io.Serializable {


     private SalesByStoreId id;

    public SalesByStore() {
    }

    public SalesByStore(SalesByStoreId id) {
       this.id = id;
    }
   
    public SalesByStoreId getId() {
        return this.id;
    }
    
    public void setId(SalesByStoreId id) {
        this.id = id;
    }




}


