package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * StaffList generated by hbm2java
 */
public class StaffList  implements java.io.Serializable {


     private StaffListId id;

    public StaffList() {
    }

    public StaffList(StaffListId id) {
       this.id = id;
    }
   
    public StaffListId getId() {
        return this.id;
    }
    
    public void setId(StaffListId id) {
        this.id = id;
    }




}


