package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * Stagiaire generated by hbm2java
 */
public class Stagiaire  implements java.io.Serializable {


     private StagiaireId id;

    public Stagiaire() {
    }

    public Stagiaire(StagiaireId id) {
       this.id = id;
    }
   
    public StagiaireId getId() {
        return this.id;
    }
    
    public void setId(StagiaireId id) {
        this.id = id;
    }




}


