package sakila;
// Generated 11 sept. 2019 22:17:12 by Hibernate Tools 5.1.10.Final



/**
 * T generated by hbm2java
 */
public class T  implements java.io.Serializable {


     private TId id;

    public T() {
    }

    public T(TId id) {
       this.id = id;
    }
   
    public TId getId() {
        return this.id;
    }
    
    public void setId(TId id) {
        this.id = id;
    }




}


